#include "names.h"

Name Names::about;
Name Names::actionType;
Name Names::actor;
Name Names::actorType;
Name Names::aiAction;
Name Names::aiBehaviour;
Name Names::aiMind;
Name Names::attack;
Name Names::attackType;
Name Names::buildPresenceLinks;
Name Names::buildRoomProxy;
Name Names::collisionModel;
Name Names::colour;
Name Names::currentEnviornment;
Name Names::deathPlayInfo;
Name Names::default_;
Name Names::defaultPostProcess;
Name Names::defaultPrimitives;
Name Names::defaultRendering;
Name Names::defaultRenderingSkinned;
Name Names::defaultRenderingSkinnedToSingleBone;
Name Names::defaultRenderingStatic;
Name Names::defaultUI;
Name Names::destroyed;
Name Names::door;
Name Names::doorType;
Name Names::environmentType;
Name Names::failed;
Name Names::fast;
Name Names::faster;
Name Names::font;
Name Names::fragmentShader;
Name Names::from;
Name Names::game;
Name Names::gameInputDefinition;
Name Names::hall;
Name Names::hub;
Name Names::id;
Name Names::immediate;
Name Names::instigator;
Name Names::item;
Name Names::itemType;
Name Names::levelType;
Name Names::material;
Name Names::mesh;
Name Names::meshSkinned;
Name Names::meshStatic;
Name Names::modelViewMatrix;
Name Names::moduleCollisionUpdateGradient;
Name Names::moduleCrawlerUpdateItemInReticle;
Name Names::movementRequestID;
Name Names::movementStyle;
Name Names::normal;
Name Names::normalMatrix;
Name Names::object;
Name Names::outColour;
Name Names::physicalMaterial;
Name Names::playInfo;
Name Names::position;
Name Names::postProcess;
Name Names::postProcessChainDefinition;
Name Names::projectile;
Name Names::projectileType;
Name Names::projectionMatrix;
Name Names::projectionMatrix0;
Name Names::projectionMatrix1;
Name Names::projectionMatrix3D;
Name Names::query;
Name Names::regionType;
Name Names::room;
Name Names::roomPart;
Name Names::roomType;
Name Names::root;
Name Names::runwayEnd;
Name Names::runwayStart;
Name Names::servant;
Name Names::shaderFunctionLib;
Name Names::shaderProgram;
Name Names::simple;
Name Names::simpleTravelPiece;
Name Names::skeleton;
Name Names::slow;
Name Names::slower;
Name Names::success;
Name Names::takeItem;
Name Names::taken;
Name Names::texture;
Name Names::time;
Name Names::travel;
Name Names::traveling;
Name Names::type;
Name Names::vertexShader;
	
void Names::initialise_static()
{
	about = Name(String(TXT("about")));
	actionType = Name(String(TXT("actionType")));
	actor = Name(String(TXT("actor")));
	actorType = Name(String(TXT("actorType")));
	aiAction = Name(String(TXT("aiAction")));
	aiBehaviour = Name(String(TXT("aiBehaviour")));
	aiMind = Name(String(TXT("aiMind")));
	attack = Name(String(TXT("attack")));
	attackType = Name(String(TXT("attackType")));
	buildPresenceLinks = Name(String(TXT("buildPresenceLinks")));
	buildRoomProxy = Name(String(TXT("buildRoomProxy")));
	collisionModel = Name(String(TXT("collisionModel")));
	colour = Name(String(TXT("colour")));
	currentEnviornment = Name(String(TXT("currentEnviornment")));
	deathPlayInfo = Name(String(TXT("death")));
	default_ = Name(String(TXT("default")));
	defaultPostProcess = Name(String(TXT("defaultPostProcess")));
	defaultPrimitives = Name(String(TXT("defaultPrimitives")));
	defaultRendering = Name(String(TXT("defaultRendering")));
	defaultRenderingSkinned = Name(String(TXT("defaultRenderingSkinned")));
	defaultRenderingSkinnedToSingleBone = Name(String(TXT("defaultRenderingSkinnedToSingleBone")));
	defaultRenderingStatic = Name(String(TXT("defaultRenderingStatic")));
	defaultUI = Name(String(TXT("defaultUI")));
	destroyed = Name(String(TXT("destroyed")));
	door = Name(String(TXT("door")));
	doorType = Name(String(TXT("doorType")));
	environmentType = Name(String(TXT("environmentType")));
	failed = Name(String(TXT("failed")));
	fast = Name(String(TXT("fast")));
	faster = Name(String(TXT("faster")));
	font = Name(String(TXT("font")));
	fragmentShader = Name(String(TXT("fragmentShader")));
	from = Name(String(TXT("from")));
	game = Name(String(TXT("game")));
	gameInputDefinition = Name(String(TXT("gameInputDefinition")));
	hall = Name(String(TXT("hall")));
	hub = Name(String(TXT("hub")));
	id = Name(String(TXT("id")));
	immediate = Name(String(TXT("immediate")));
	instigator = Name(String(TXT("instigator")));
	item = Name(String(TXT("item")));
	itemType = Name(String(TXT("itemType")));
	levelType = Name(String(TXT("levelType")));
	material = Name(String(TXT("material")));
	mesh = Name(String(TXT("mesh")));
	meshSkinned = Name(String(TXT("meshSkinned")));
	meshStatic = Name(String(TXT("meshStatic")));
	modelViewMatrix = Name(String(TXT("modelViewMatrix")));
	moduleCollisionUpdateGradient = Name(String(TXT("moduleCollisionUpdateGradient")));
	moduleCrawlerUpdateItemInReticle = Name(String(TXT("moduleCrawlerUpdateItemInReticle")));
	movementRequestID = Name(String(TXT("movementRequestID")));
	movementStyle = Name(String(TXT("movementStyle")));
	normal = Name(String(TXT("normal")));
	normalMatrix = Name(String(TXT("normalMatrix")));
	object = Name(String(TXT("object")));
	outColour = Name(String(TXT("outColour")));
	physicalMaterial = Name(String(TXT("physicalMaterial")));
	playInfo = Name(String(TXT("playInfo")));
	position = Name(String(TXT("position")));
	postProcess = Name(String(TXT("postProcess")));
	postProcessChainDefinition = Name(String(TXT("postProcessChainDefinition")));
	projectile = Name(String(TXT("projectile")));
	projectileType = Name(String(TXT("projectileType")));
	projectionMatrix = Name(String(TXT("projectionMatrix")));
	projectionMatrix0 = Name(String(TXT("projectionMatrix0")));
	projectionMatrix1 = Name(String(TXT("projectionMatrix1")));
	projectionMatrix3D = Name(String(TXT("projectionMatrix3D")));
	query = Name(String(TXT("query")));
	regionType = Name(String(TXT("regionType")));
	room = Name(String(TXT("room")));
	roomPart = Name(String(TXT("roomPart")));
	roomType = Name(String(TXT("roomType")));
	root = Name(String(TXT("root")));
	runwayEnd = Name(String(TXT("runwayEnd")));
	runwayStart = Name(String(TXT("runwayStart")));
	servant = Name(String(TXT("servant")));
	shaderFunctionLib = Name(String(TXT("shaderFunctionLib")));
	shaderProgram = Name(String(TXT("shaderProgram")));
	simple = Name(String(TXT("simple")));
	simpleTravelPiece = Name(String(TXT("simpleTravelPiece")));
	skeleton = Name(String(TXT("skeleton")));
	slow = Name(String(TXT("slow")));
	slower = Name(String(TXT("slower")));
	success = Name(String(TXT("success")));
	takeItem = Name(String(TXT("takeItem")));
	taken = Name(String(TXT("taken")));
	texture = Name(String(TXT("texture")));
	time = Name(String(TXT("time")));
	travel = Name(String(TXT("travel")));
	traveling = Name(String(TXT("traveling")));
	type = Name(String(TXT("type")));
	vertexShader = Name(String(TXT("vertexShader")));
}
